#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  4 21:33:27 2020

@author: Rahul.Deb.Das@ibm.com
"""

from geopy.geocoders import Nominatim
import geocoder

address='Mies-van-der-Rohe-Strasse 6, 80807 München' #replace this with the queried address. You can also batch process the entire code for more than one query.

url = 'http://localhost/nominatim/'

g = geocoder.osm(address)

if (bool(g.osm)==True):
    lon=g.osm['x']
    lat=g.osm['y']
    state=g.osm['addr:state']
    country=g.osm['addr:country']
        
    print (address,',',lat,',',lon,',',state,',',country)
else:
    print ('address not found!')
